name: Comply Action
description: Run strongdm/comply tasks such as scheduler
branding:
  color: purple
  icon: clipboard
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  jira_username:
    required: false
    description: Username for JIRA account
  jira_password:
    required: false
    description: Password (or API token) for JIRA account
  comply_folder:
    description: 'Folder path to switch to to find the Comply workspace'
    required: false
